// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTPMuEoxiw_q6LREPldFkrxhOwEbcakE',
    appId: '1:642483586949:android:4e60321288495d710066ec',
    messagingSenderId: '642483586949',
    projectId: 'portals-slj8vs',
    storageBucket: 'portals-slj8vs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSUt-MO1mxyswWk1-gFfeKZCmxLJNbGPk',
    appId: '1:642483586949:ios:435e105b2ccf7fa50066ec',
    messagingSenderId: '642483586949',
    projectId: 'portals-slj8vs',
    storageBucket: 'portals-slj8vs.appspot.com',
    iosBundleId: 'com.example.portals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhnmHfVp_qGgWBg6KZk4PtPfvVx8bsx2E',
    appId: '1:642483586949:web:670235b76a4ff8d60066ec',
    messagingSenderId: '642483586949',
    projectId: 'portals-slj8vs',
    authDomain: 'portals-slj8vs.firebaseapp.com',
    storageBucket: 'portals-slj8vs.appspot.com',
  );
}
